import User from '../db/user.js';
import Article from '../db/articles.js';
import Comment from '../db/comment.js';

const insertDummyData = async () => {
  try {
    const existingUser = await User.findOne({ name: 'autogeneratedUser' });
    if (!existingUser) {
      const dummyUser = new User({
        name: 'autogeneratedUser',
        password: 'password', // This should be hashed in a real app
        editor: true,
      });
      await dummyUser.save();

      const dummyArticles = [];
      for (let i = 1; i <= 5; i++) {
        dummyArticles.push({
          title: `Dummy Article ${i}`,
          content: 'Lorem Ipsum '.repeat(10).slice(0, 200), // Generate Lorem Ipsum text up to 200 characters
          author: dummyUser._id,
        });
      }
      const createdArticles = await Article.insertMany(dummyArticles);

      const dummyComments = [];
      createdArticles.forEach((article) => {
        for (let i = 0; i < 2; i++) {
          dummyComments.push({
            content: 'Lorem Ipsum '.repeat(5).slice(0, 100), // Generate Lorem Ipsum text up to 100 characters
            author: dummyUser._id,
            article: article._id,
          });
        }
      });
      await Comment.insertMany(dummyComments);
    }
  } catch (error) {
    console.error('Error inserting dummy data:', error);
  }
};

export default insertDummyData;
